# Default values for cloudbolt-collector-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
DEBUG: ""
IMAGE_VERSION: ""
INGESTION_API_URL: ""
# Optional: Base URL for Prometheus and CoreAPI (e.g. "http://prometheus.monitoring.svc.cluster.local:9090")
PROMETHEUS_BASE_URL: ""
COREAPI_BASE_URL: ""
clusterRole:
  # Set to true to create a ClusterRoles for the collector
  create: false
image:
  repository: cloudboltsoftware/cloudbolt-collector
  pullPolicy: Always
  tag: v0.53.0
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: "RuntimeDefault"
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  runAsNonRoot: true
  runAsUser:
  seccompProfile:
    type: "RuntimeDefault"
service:
  type: ClusterIP
  port: 8000
liveness:
  httpGet_path: /health/
  httpGet_port: 8000
  initialDelaySeconds: 300
  failureThreshold: 3
  periodSeconds: 300
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
