# Default values for cloudbolt-collector-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
DEBUG: ""
IMAGE_VERSION: ""
OCP_IP: ""
OCP_PORT: ""
OCP_SERVICENAME: ""
OCP_ENABLE_SSL_VERIFICATION: ""
INGESTION_API_URL: ""
SERVICE_ACCOUNT_NAME: ""
image:
  repository: cloudboltsoftware/cloudbolt-collector
  pullPolicy: Always
  tag: "v0.23.0"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: "RuntimeDefault"
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  runAsNonRoot: true
  seccompProfile:
    type: "RuntimeDefault"
service:
  type: ClusterIP
  port: 8000
liveness:
  initialDelaySeconds: 300
  failureThreshold: 3
  periodSeconds: 300
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
