{{- if .Values.serviceAccount.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cloudbolt-collector-helm.fullname" . }}-clusterreader-clusterrolebinding
  labels:
    {{- include "cloudbolt-collector-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudbolt-collector-helm.serviceAccountName" . }}
    namespace: {{ include "cloudbolt-collector-helm.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cloudbolt-collector-helm.fullname" . }}-admin-clusterrolebinding
  labels:
    {{- include "cloudbolt-collector-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudbolt-collector-helm.serviceAccountName" . }}
    namespace: {{ include "cloudbolt-collector-helm.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudbolt-collector-helm.fullname" . }}-pv-access
  labels:
    {{- include "cloudbolt-collector-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudbolt-collector-helm.fullname" . }}-pv-access
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudbolt-collector-helm.serviceAccountName" . }}
    namespace: {{ include "cloudbolt-collector-helm.namespace" . }}

---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudbolt-collector-helm.fullname" . }}-nodes-access
  labels:
    {{- include "cloudbolt-collector-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudbolt-collector-helm.fullname" . }}-nodes-access
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudbolt-collector-helm.serviceAccountName" . }}
    namespace: {{ include "cloudbolt-collector-helm.namespace" . }}
