apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloudbolt-collector-helm.fullname" . }}-nodes-access
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
